## Preprossing TCGA-LUAD non-omics data

In [38]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer

In [40]:
data = pd.read_csv("D:/NCKH/CURE/data/tcga-luad/luad_tcga_pan_can_atlas_2018_clinical_data.tsv", sep="\t")

In [41]:
data = data.rename(columns={'Sample ID': 'SAMPLE_ID'})

In [42]:
data.columns

Index(['Study ID', 'Patient ID', 'SAMPLE_ID', 'Diagnosis Age',
       'Neoplasm Disease Stage American Joint Committee on Cancer Code',
       'American Joint Committee on Cancer Publication Version Type',
       'Aneuploidy Score', 'Buffa Hypoxia Score', 'Cancer Type',
       'TCGA PanCanAtlas Cancer Type Acronym', 'Cancer Type Detailed',
       'Last Communication Contact from Initial Pathologic Diagnosis Date',
       'Birth from Initial Pathologic Diagnosis Date',
       'Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value',
       'Disease Free (Months)', 'Disease Free Status',
       'Months of disease-specific survival',
       'Disease-specific Survival status', 'Ethnicity Category',
       'Form completion date', 'Fraction Genome Altered',
       'Genetic Ancestry Label', 'Neoplasm Histologic Grade',
       'Neoadjuvant Therapy Type Administered Prior To Resection Text',
       'ICD-10 Classification',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code',
       'In PanCan Pathway Analysis', 'Informed consent verified',
       'MSI MANTIS Score', 'MSIsensor Score', 'Mutation Count',
       'New Neoplasm Event Post Initial Therapy Indicator', 'Oncotree Code',
       'Overall Survival (Months)', 'Overall Survival Status',
       'Other Patient ID',
       'American Joint Committee on Cancer Metastasis Stage Code',
       'Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code',
       'American Joint Committee on Cancer Tumor Stage Code',
       'Person Neoplasm Cancer Status', 'Progress Free Survival (Months)',
       'Progression Free Status', 'Primary Lymph Node Presentation Assessment',
       'Prior Diagnosis', 'Race Category', 'Radiation Therapy',
       'Ragnum Hypoxia Score', 'Number of Samples Per Patient', 'Sample Type',
       'Sex', 'Somatic Status', 'Subtype', 'Tumor Break Load',
       'Tissue Prospective Collection Indicator',
       'Tissue Retrospective Collection Indicator', 'Tissue Source Site',
       'Tissue Source Site Code', 'TMB (nonsynonymous)',
       'Tumor Disease Anatomic Site', 'Tumor Type', 'Patient Weight',
       'Winter Hypoxia Score'],
      dtype='object')

In [43]:
print(data.isna().sum().sort_values(ascending=False).to_string())

Neoplasm Histologic Grade                                                                      566
Patient Weight                                                                                 566
Primary Lymph Node Presentation Assessment                                                     566
Disease Free (Months)                                                                          265
Disease Free Status                                                                            262
Ethnicity Category                                                                             176
Last Communication Contact from Initial Pathologic Diagnosis Date                              174
Person Neoplasm Cancer Status                                                                  145
New Neoplasm Event Post Initial Therapy Indicator                                              117
Race Category                                                                                  117
Radiation Therapy                                                                               99
Disease-specific Survival status                                                                88
Birth from Initial Pathologic Diagnosis Date                                                    83
American Joint Committee on Cancer Publication Version Type                                     73
Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value                          71
Diagnosis Age                                                                                   71
Fraction Genome Altered                                                                         66
Aneuploidy Score                                                                                65
Subtype                                                                                         64
Months of disease-specific survival                                                             61
Overall Survival (Months)                                                                       61
Progress Free Survival (Months)                                                                 61
Tissue Prospective Collection Indicator                                                         59
Tissue Retrospective Collection Indicator                                                       59
American Joint Committee on Cancer Metastasis Stage Code                                        56
Ragnum Hypoxia Score                                                                            56
Winter Hypoxia Score                                                                            56
Buffa Hypoxia Score                                                                             56
Neoplasm Disease Stage American Joint Committee on Cancer Code                                  54
Tumor Break Load                                                                                53
Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code                       53
Informed consent verified                                                                       52
Progression Free Status                                                                         52
Tumor Disease Anatomic Site                                                                     52
American Joint Committee on Cancer Tumor Stage Code                                             52
Form completion date                                                                            52
Other Patient ID                                                                                52
Overall Survival Status                                                                         52
Neoadjuvant Therapy Type Administered Prior To Resection Text                                   52
ICD-10 Classification                                                                           52
International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code     52
Sex                                                                                             52
International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code          52
Prior Diagnosis                                                                                 52
Genetic Ancestry Label                                                                           6
Mutation Count                                                                                   5
MSI MANTIS Score                                                                                 2
MSIsensor Score                                                                                  1
Oncotree Code                                                                                    0
Tissue Source Site                                                                               0
SAMPLE_ID                                                                                        0
Tumor Type                                                                                       0
Cancer Type                                                                                      0
TMB (nonsynonymous)                                                                              0
Tissue Source Site Code                                                                          0
Cancer Type Detailed                                                                             0
TCGA PanCanAtlas Cancer Type Acronym                                                             0
Patient ID                                                                                       0
In PanCan Pathway Analysis                                                                       0
Somatic Status                                                                                   0
Sample Type                                                                                      0
Number of Samples Per Patient                                                                    0
Study ID                                                                                         0

In [44]:
data = data.dropna(subset=['Overall Survival (Months)'])

In [45]:
print(data.isna().sum().sort_values(ascending=False).to_string())

Patient Weight                                                                                 505
Primary Lymph Node Presentation Assessment                                                     505
Neoplasm Histologic Grade                                                                      505
Disease Free Status                                                                            204
Disease Free (Months)                                                                          204
Ethnicity Category                                                                             115
Last Communication Contact from Initial Pathologic Diagnosis Date                              113
Person Neoplasm Cancer Status                                                                   92
New Neoplasm Event Post Initial Therapy Indicator                                               63
Race Category                                                                                   56
Radiation Therapy                                                                               47
Disease-specific Survival status                                                                35
Birth from Initial Pathologic Diagnosis Date                                                    22
American Joint Committee on Cancer Publication Version Type                                     19
Fraction Genome Altered                                                                         14
Subtype                                                                                         12
Aneuploidy Score                                                                                12
Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value                          10
Diagnosis Age                                                                                   10
Tissue Prospective Collection Indicator                                                          7
Tissue Retrospective Collection Indicator                                                        7
Genetic Ancestry Label                                                                           6
Mutation Count                                                                                   5
Ragnum Hypoxia Score                                                                             4
American Joint Committee on Cancer Metastasis Stage Code                                         4
Winter Hypoxia Score                                                                             4
Buffa Hypoxia Score                                                                              4
Neoplasm Disease Stage American Joint Committee on Cancer Code                                   2
MSI MANTIS Score                                                                                 2
MSIsensor Score                                                                                  1
Tumor Break Load                                                                                 1
Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code                        1
Number of Samples Per Patient                                                                    0
Sample Type                                                                                      0
Sex                                                                                              0
Somatic Status                                                                                   0
Cancer Type                                                                                      0
International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code           0
Cancer Type Detailed                                                                             0
Tissue Source Site                                                                               0
Tissue Source Site Code                                                                          0
TMB (nonsynonymous)                                                                              0
Tumor Disease Anatomic Site                                                                      0
Tumor Type                                                                                       0
SAMPLE_ID                                                                                        0
TCGA PanCanAtlas Cancer Type Acronym                                                             0
Prior Diagnosis                                                                                  0
Months of disease-specific survival                                                              0
In PanCan Pathway Analysis                                                                       0
Form completion date                                                                             0
Progression Free Status                                                                          0
Progress Free Survival (Months)                                                                  0
Neoadjuvant Therapy Type Administered Prior To Resection Text                                    0
American Joint Committee on Cancer Tumor Stage Code                                              0
ICD-10 Classification                                                                            0
Other Patient ID                                                                                 0
Overall Survival Status                                                                          0
Overall Survival (Months)                                                                        0
Oncotree Code                                                                                    0
International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code      0
Patient ID                                                                                       0
Informed consent verified                                                                        0
Study ID                                                                                         0

In [46]:
drop_cols = ["Patient Weight", "Primary Lymph Node Presentation Assessment", "Neoplasm Histologic Grade", "Disease Free Status", "Disease Free (Months)", "Subtype",
             "Cancer Type", "Cancer Type Detailed", "Number of Samples Per Patient", "Oncotree Code", "Sample Type", "Somatic Status",
             "TCGA PanCanAtlas Cancer Type Acronym", "Tumor Disease Anatomic Site", "Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value",
             "Informed consent verified", "Progression Free Status", "Progress Free Survival (Months)", "Prior Diagnosis", "Study ID", "Ethnicity Category",
             "American Joint Committee on Cancer Publication Version Type", "Informed consent verified", "In PanCan Pathway Analysis", "Tissue Source Site",
             "Tissue Source Site Code", "Form completion date", "Disease-specific Survival status", "Months of disease-specific survival",
             'Tissue Prospective Collection Indicator', 'Tissue Retrospective Collection Indicator']

In [47]:
data = data.drop(drop_cols, axis=1)

In [48]:
data.shape

(505, 33)

In [49]:
data.columns

Index(['Patient ID', 'SAMPLE_ID', 'Diagnosis Age',
       'Neoplasm Disease Stage American Joint Committee on Cancer Code',
       'Aneuploidy Score', 'Buffa Hypoxia Score',
       'Last Communication Contact from Initial Pathologic Diagnosis Date',
       'Birth from Initial Pathologic Diagnosis Date',
       'Fraction Genome Altered', 'Genetic Ancestry Label',
       'Neoadjuvant Therapy Type Administered Prior To Resection Text',
       'ICD-10 Classification',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code',
       'MSI MANTIS Score', 'MSIsensor Score', 'Mutation Count',
       'New Neoplasm Event Post Initial Therapy Indicator',
       'Overall Survival (Months)', 'Overall Survival Status',
       'Other Patient ID',
       'American Joint Committee on Cancer Metastasis Stage Code',
       'Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code',
       'American Joint Committee on Cancer Tumor Stage Code',
       'Person Neoplasm Cancer Status', 'Race Category', 'Radiation Therapy',
       'Ragnum Hypoxia Score', 'Sex', 'Tumor Break Load',
       'TMB (nonsynonymous)', 'Tumor Type', 'Winter Hypoxia Score'],
      dtype='object')

# Numerical

In [50]:
missing_cols = [col for col in data.columns if data[col].isna().sum() > 0]
missing_cols

['Diagnosis Age',
 'Neoplasm Disease Stage American Joint Committee on Cancer Code',
 'Aneuploidy Score',
 'Buffa Hypoxia Score',
 'Last Communication Contact from Initial Pathologic Diagnosis Date',
 'Birth from Initial Pathologic Diagnosis Date',
 'Fraction Genome Altered',
 'Genetic Ancestry Label',
 'MSI MANTIS Score',
 'MSIsensor Score',
 'Mutation Count',
 'New Neoplasm Event Post Initial Therapy Indicator',
 'American Joint Committee on Cancer Metastasis Stage Code',
 'Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code',
 'Person Neoplasm Cancer Status',
 'Race Category',
 'Radiation Therapy',
 'Ragnum Hypoxia Score',
 'Tumor Break Load',
 'Winter Hypoxia Score']

In [51]:
s = data[missing_cols].dtypes != 'object'
missing_num_cols = list(s[s].index)

missing_num_cols

['Diagnosis Age',
 'Aneuploidy Score',
 'Buffa Hypoxia Score',
 'Last Communication Contact from Initial Pathologic Diagnosis Date',
 'Birth from Initial Pathologic Diagnosis Date',
 'Fraction Genome Altered',
 'MSI MANTIS Score',
 'MSIsensor Score',
 'Mutation Count',
 'Ragnum Hypoxia Score',
 'Tumor Break Load',
 'Winter Hypoxia Score']

In [52]:
num_imputer = SimpleImputer(strategy='median')

In [53]:
data[missing_num_cols] = num_imputer.fit_transform(data[missing_num_cols])

# Categorical
## Ordinal

In [54]:
ID_cols = ['Patient ID', 'SAMPLE_ID']

In [55]:
s = data.dtypes == 'object'
cat_cols_with_ids = list(s[s].index)
cat_cols = [col for col in cat_cols_with_ids if col not in ID_cols]
cat_cols

['Neoplasm Disease Stage American Joint Committee on Cancer Code',
 'Genetic Ancestry Label',
 'Neoadjuvant Therapy Type Administered Prior To Resection Text',
 'ICD-10 Classification',
 'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code',
 'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code',
 'New Neoplasm Event Post Initial Therapy Indicator',
 'Overall Survival Status',
 'Other Patient ID',
 'American Joint Committee on Cancer Metastasis Stage Code',
 'Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code',
 'American Joint Committee on Cancer Tumor Stage Code',
 'Person Neoplasm Cancer Status',
 'Race Category',
 'Radiation Therapy',
 'Sex',
 'Tumor Type']

In [56]:
# Get number of unique entries in each column with categorical data
object_nunique = list(map(lambda col: data[col].nunique(), cat_cols))
d = dict(zip(cat_cols, object_nunique))

# Print number of unique entries by column, in ascending order
sorted(d.items(), key=lambda x: x[1])

[('Neoadjuvant Therapy Type Administered Prior To Resection Text', 2),
 ('New Neoplasm Event Post Initial Therapy Indicator', 2),
 ('Overall Survival Status', 2),
 ('Person Neoplasm Cancer Status', 2),
 ('Radiation Therapy', 2),
 ('Sex', 2),
 ('Race Category', 4),
 ('Genetic Ancestry Label', 5),
 ('American Joint Committee on Cancer Metastasis Stage Code', 5),
 ('Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code',
  5),
 ('International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code',
  6),
 ('ICD-10 Classification', 7),
 ('Neoplasm Disease Stage American Joint Committee on Cancer Code', 9),
 ('American Joint Committee on Cancer Tumor Stage Code', 9),
 ('International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code',
  12),
 ('Tumor Type', 12),
 ('Other Patient ID', 505)]

In [57]:
# Too many values
too_many_unique_val_cols = ['Tumor Type', 'Other Patient ID']

In [58]:
data = data.drop(too_many_unique_val_cols, axis=1)

In [59]:
# Columns where order matters! (or just pure binary)
ordinal_cols = [col for col in data.columns if data[col].nunique() == 2]
ordinal_cols.extend(['American Joint Committee on Cancer Metastasis Stage Code', 'Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code',
                     'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code', 'ICD-10 Classification',
                     'Neoplasm Disease Stage American Joint Committee on Cancer Code', 'American Joint Committee on Cancer Tumor Stage Code',
                     'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code'])

In [60]:
ordinal_encoder = OrdinalEncoder() 
cat_imputer = SimpleImputer(strategy='constant', fill_value=-1)

In [61]:
data[ordinal_cols] = ordinal_encoder.fit_transform(data[ordinal_cols])
data[ordinal_cols] = cat_imputer.fit_transform(data[ordinal_cols])

## One-hot

In [62]:
# Resetting index to concat with one-hot encoded data later
data = data.reset_index(drop=True)

In [63]:
s = data.dtypes == 'object'

OH_cols = [col for col in list(s[s].index) if col not in ID_cols]
OH_cols

['Genetic Ancestry Label', 'Race Category']

In [64]:
data[OH_cols].isna().sum().sort_values()

Genetic Ancestry Label     6
Race Category             56
dtype: int64

In [65]:
OH_imputer = SimpleImputer(strategy='constant')
OH_encoder = OneHotEncoder(sparse_output=False)

In [66]:
data[OH_cols] = OH_imputer.fit_transform(data[OH_cols])
data[OH_cols]

    Genetic Ancestry Label              Race Category
0                      EUR              missing_value
1                      EUR              missing_value
2                      EUR              missing_value
3                      EUR              missing_value
4                      EUR              missing_value
..                     ...                        ...
500                    EUR                      White
501                    EUR                      White
502              AFR_ADMIX  Black or African American
503                    EUR                      White
504                    AFR  Black or African American

[505 rows x 2 columns]

In [67]:
encoded_OH_data = pd.DataFrame(OH_encoder.fit_transform(data[OH_cols]))
encoded_OH_data.columns = OH_encoder.get_feature_names_out()
# print(encoded_OH_data.dtypes.to_string())

In [68]:
data = data.drop(OH_cols, axis=1)

In [69]:
data = pd.concat([data, encoded_OH_data], axis=1)

In [70]:
data

,Patient ID,SAMPLE_ID,Diagnosis Age,Neoplasm Disease Stage American Joint Committee on Cancer Code,Aneuploidy Score,Buffa Hypoxia Score,Last Communication Contact from Initial Pathologic Diagnosis Date,Birth from Initial Pathologic Diagnosis Date,Fraction Genome Altered,Neoadjuvant Therapy Type Administered Prior To Resection Text,...,Genetic Ancestry Label_AFR_ADMIX,Genetic Ancestry Label_AMR,Genetic Ancestry Label_EAS,Genetic Ancestry Label_EUR,Genetic Ancestry Label_missing_value,Race Category_American Indian or Alaska Native,Race Category_Asian,Race Category_Black or African American,Race Category_White,Race Category_missing_value
0,TCGA-05-4244,TCGA-05-4244-01,70.0,8.0,17.0,11.0,0.0,-25752.0,0.4565,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,TCGA-05-4249,TCGA-05-4249-01,67.0,2.0,24.0,-27.0,1523.0,-24532.0,0.2221,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,TCGA-05-4250,TCGA-05-4250-01,79.0,6.0,17.0,29.0,620.5,-29068.0,0.2362,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,TCGA-05-4382,TCGA-05-4382-01,68.0,2.0,22.0,19.0,607.0,-24868.0,0.0854,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,TCGA-05-4384,TCGA-05-4384-01,66.0,6.0,1.0,-37.0,426.0,-24411.0,0.0661,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,TCGA-NJ-A55O,TCGA-NJ-A55O-01,56.0,4.0,16.0,-27.0,13.0,-20628.0,0.0194,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
501,TCGA-NJ-A55R,TCGA-NJ-A55R-01,67.0,1.0,21.0,-11.0,603.0,-24738.0,0.0760,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
502,TCGA-NJ-A7XG,TCGA-NJ-A7XG-01,49.0,6.0,16.0,-21.0,617.0,-18127.0,0.4205,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
503,TCGA-O1-A52J,TCGA-O1-A52J-01,74.0,1.0,29.0,-23.0,620.5,-27223.0,0.5443,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
504,TCGA-S2-AA1A,TCGA-S2-AA1A-01,68.0,1.0,16.0,-31.0,513.0,-24903.0,0.0598,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [71]:
print(data.columns)
print(len(data.columns))

Index(['Patient ID', 'SAMPLE_ID', 'Diagnosis Age',
       'Neoplasm Disease Stage American Joint Committee on Cancer Code',
       'Aneuploidy Score', 'Buffa Hypoxia Score',
       'Last Communication Contact from Initial Pathologic Diagnosis Date',
       'Birth from Initial Pathologic Diagnosis Date',
       'Fraction Genome Altered',
       'Neoadjuvant Therapy Type Administered Prior To Resection Text',
       'ICD-10 Classification',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code',
       'MSI MANTIS Score', 'MSIsensor Score', 'Mutation Count',
       'New Neoplasm Event Post Initial Therapy Indicator',
       'Overall Survival (Months)', 'Overall Survival Status',
       'American Joint Committee on Cancer Metastasis Stage Code',
       'Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code',
       'American Joint Committee on Cancer Tumor Stage Code',
       'Person Neoplasm Cancer Status', 'Radiation Therapy',
       'Ragnum Hypoxia Score', 'Sex', 'Tumor Break Load',
       'TMB (nonsynonymous)', 'Winter Hypoxia Score',
       'Genetic Ancestry Label_AFR', 'Genetic Ancestry Label_AFR_ADMIX',
       'Genetic Ancestry Label_AMR', 'Genetic Ancestry Label_EAS',
       'Genetic Ancestry Label_EUR', 'Genetic Ancestry Label_missing_value',
       'Race Category_American Indian or Alaska Native', 'Race Category_Asian',
       'Race Category_Black or African American', 'Race Category_White',
       'Race Category_missing_value'],
      dtype='object')
40

In [72]:
demographics_cols = ['SAMPLE_ID',
    "Diagnosis Age",
    "Birth from Initial Pathologic Diagnosis Date",
    "Sex",
    "Race Category_American Indian or Alaska Native",
    "Race Category_Asian",
    "Race Category_Black or African American",
    "Race Category_White",
    "Race Category_missing_value",
    "Genetic Ancestry Label_AFR",
    "Genetic Ancestry Label_AFR_ADMIX",
    "Genetic Ancestry Label_AMR",
    "Genetic Ancestry Label_EAS",
    "Genetic Ancestry Label_EUR",
    "Genetic Ancestry Label_missing_value"
]

clinical_cols = ['SAMPLE_ID',
    "Neoplasm Disease Stage American Joint Committee on Cancer Code",
    "American Joint Committee on Cancer Metastasis Stage Code",
    "Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code",
    "American Joint Committee on Cancer Tumor Stage Code",
    "ICD-10 Classification",
    "International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code",
    "International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code",
    "Person Neoplasm Cancer Status",
    "New Neoplasm Event Post Initial Therapy Indicator",
    "Neoadjuvant Therapy Type Administered Prior To Resection Text",
    "Last Communication Contact from Initial Pathologic Diagnosis Date"
]

paraclinical_cols = ['SAMPLE_ID',
    "Aneuploidy Score",
    "Buffa Hypoxia Score",
    "Fraction Genome Altered",
    "MSI MANTIS Score",
    "MSIsensor Score",
    "Mutation Count",
    "Ragnum Hypoxia Score",
    "Winter Hypoxia Score",
    "Tumor Break Load",
    "TMB (nonsynonymous)"
]

treatment_cols = ['SAMPLE_ID', "Radiation Therapy"]

output_cols = ['SAMPLE_ID', "Overall Survival (Months)", "Overall Survival Status"]

In [73]:
luad_demographics = data[demographics_cols]
luad_clinical = data[clinical_cols]
luad_paraclinical = data[paraclinical_cols]
luad_treatment = data[treatment_cols]
luad_output = data[output_cols]

In [74]:
data.to_csv('preprocessed_luad_non_omics.csv', index=False)
luad_demographics.to_csv('preprocessed_luad_demographics.csv', index=False)
luad_clinical.to_csv('preprocessed_luad_clinical.csv', index=False)
luad_paraclinical.to_csv('preprocessed_luad_paraclinical.csv', index=False)
luad_treatment.to_csv('preprocessed_luad_treatment.csv', index=False)
luad_output.to_csv('preprocessed_luad_output.csv', index=False)